[Frontend] ENV: gremlin-dashboard
[Frontend] CWD: /home/runner/work/GremlinGPT/GremlinGPT
[Frontend] PYTHONPATH: /home/runner/work/GremlinGPT/GremlinGPT:/home/runner/work/GremlinGPT/GremlinGPT
[Frontend] Running: python3 -m http.server 8080 --directory frontend
[Frontend] Started with PID: 5399
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/gremlin-dashboard/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/share/miniconda/envs/gremlin-dashboard/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/share/miniconda/envs/gremlin-dashboard/lib/python3.9/http/server.py", line 1308, in <module>
    test(
  File "/usr/share/miniconda/envs/gremlin-dashboard/lib/python3.9/http/server.py", line 1259, in test
    with ServerClass(addr, HandlerClass) as httpd:
  File "/usr/share/miniconda/envs/gremlin-dashboard/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/share/miniconda/envs/gremlin-dashboard/lib/python3.9/http/server.py", line 1302, in server_bind
    return super().server_bind()
  File "/usr/share/miniconda/envs/gremlin-dashboard/lib/python3.9/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/share/miniconda/envs/gremlin-dashboard/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
[Frontend] Process exited with code 0
